image: julia:1.7 # image comes from Docker hub

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - pluto_state_cache/

pages:
  stage: deploy
  script:
    - julia -e 'using Pkg;
      Pkg.activate(mktempdir());
      Pkg.add([
      Pkg.PackageSpec(name="PlutoSliderServer", version="0.2"),
      ]);

      import PlutoSliderServer;

      PlutoSliderServer.github_action(;
      Export_cache_dir="pluto_state_cache",
      );'
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
